elfin_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - elfin_joint1
     - elfin_joint2
     - elfin_joint3
     - elfin_joint4
     - elfin_joint5
     - elfin_joint6
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.1
      elfin_joint1: {trajectory: 0.1, goal: 0.1}
      elfin_joint2: {trajectory: 0.1, goal: 0.1}
      elfin_joint3: {trajectory: 0.1, goal: 0.1}
      elfin_joint4: {trajectory: 0.1, goal: 0.1}
      elfin_joint5: {trajectory: 0.1, goal: 0.1}
      elfin_joint6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.05
  state_publish_rate:  25
  action_monitor_rate: 10
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - elfin_joint1
     - elfin_joint2
     - elfin_joint3
     - elfin_joint4
     - elfin_joint5
     - elfin_joint6

